update api path to use account id and environment in path parameters
acquia/perz-api-php pull request #3
Opened 2022-03-07 18:53 UTC by kk5190

**Motivation**
update api path to use account id and environment in path parameters

2022-03-15 14:38 UTC, kaynenh requested changes
One minor question about version number here

2022-03-15 14:38 UTC, kaynenh commented on src/PerzApiPhpClient.php
> +    $uri = '/v3/accounts/' . $account_id . '/environments/' . $environment . '/contents';
Are we okay with a hardcoded version number?

2022-03-15 17:03 UTC, scor commented on src/PerzApiPhpClient.php
> +    $uri = '/v3/accounts/' . $account_id . '/environments/' . $environment . '/contents';
we could make it a constant in PHP I suppose.

2022-03-15 17:14 UTC, scor commented on src/PerzApiPhpClient.php
>     * Get entities in Personalization.
from Personalization

2022-03-16 14:16 UTC, kk5190 commented on src/PerzApiPhpClient.php
>     * Get entities in Personalization.
updated

2022-03-16 14:17 UTC, kk5190 commented on src/PerzApiPhpClient.php
> +    $uri = '/v3/accounts/' . $account_id . '/environments/' . $environment . '/contents';
updated : defined a constant for api version

2022-03-24 20:49 UTC, japerry approved these changes

2022-03-24 20:49 UTC, japerry commented on README.md
> -## Version Information
While I'm okay with this for the PR, I added a new ticket to get this readme updated to CIS api endpoint information. https://backlog.acquia.com/browse/DIT-630

2022-03-24 20:49 UTC, merged